name: "First workflow"

on:
  workflow_dispatch:
  
  push:
    branches:
      - main
      - master
      - develop
      - feature/*
jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.3
      
      - name: Install
        run: npm install

